# Generated by Django 5.0.6 on 2024-12-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
